source 'https://rubygems.org'

gem 'fast-stemmer'
gem 'hitimes'
gem 'redcarpet'
gem 'snappy'
gem 'pg'
gem 'mysql2'
gem 'puma', :platforms => :ruby
gem 'kgio', :platforms => :ruby
gem 'raindrops', :platforms => :ruby
gem 'unicorn', :platforms => :ruby
gem 'curses', :platforms => :ruby
gem 'bson', '= 4.1.1'
gem 'eventmachine', '= 1.2.0.1'
gem 'ffi', '= 1.9.14'
gem 'json', '= 1.8.6'
gem 'nokogiri', '= 1.6.8.1'
gem 'oj', '= 2.17.4'
gem 'thin', '= 1.7.0'
gem 'bcrypt', '= 3.1.10', :platforms => :ruby
gem 'unf_ext', '= 0.0.7.2'
